import Foundation
import Testing

@testable import RailCore

/// The port's only real acceptance test: both implementations read the same
/// inputs from `port-fixtures/` and must produce the same answers.
///
/// The fixtures are generated by `app/scripts/build/build-port-fixtures.mjs`
/// from the running JavaScript, and the expected values are *whatever that
/// code returns today* — not a second opinion about what is correct. So a
/// failure here means exactly one thing: this Swift disagrees with the app it
/// was forked from. Whether the JavaScript or the Swift is "right" is a
/// separate conversation, and one that can only be had once the disagreement
/// is visible.
struct FixtureParityTests {

    // MARK: - loading

    /// Locates `port-fixtures/` by walking up from this source file.
    ///
    /// Deliberately not an SPM resource bundle: the fixtures are shared with
    /// the JavaScript side and live at the repository root, which is the point
    /// — a copy inside the package would be a copy that can drift.
    static func fixture(_ name: String) throws -> Data {
        var directory = URL(filePath: #filePath).deletingLastPathComponent()
        for _ in 0..<8 {
            let candidate = directory.appending(path: "port-fixtures/\(name)")
            if FileManager.default.fileExists(atPath: candidate.path) {
                return try Data(contentsOf: candidate)
            }
            directory = directory.deletingLastPathComponent()
        }
        Issue.record(
            """
            port-fixtures/\(name) not found above \(#filePath).
            Generate it with:  cd app && node scripts/build/build-port-fixtures.mjs
            """
        )
        throw CocoaError(.fileNoSuchFile)
    }

    static func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        try JSONDecoder().decode(type, from: fixture(name))
    }

    // MARK: - coordinates

    struct CoordsFixture: Decodable {
        struct Case: Decodable {
            let coord: [Double]
            let quant5: [Double]
            let coordKey: String
            let normalized: [Double]
        }
        struct SegmentCase: Decodable {
            let a: [Double]
            let b: [Double]
            let key: String
        }
        let cases: [Case]
        let segmentKeys: [SegmentCase]
    }

    @Test("quant5 lands on the same 5-decimal grid value")
    func quantisation() throws {
        let fixture = try Self.decode(CoordsFixture.self, "coords.json")
        #expect(fixture.cases.count > 100)
        for item in fixture.cases {
            let coordinate = try #require(Coordinate(pair: item.coord))
            #expect(Grid.quant5(coordinate.lon).bitPattern == item.quant5[0].bitPattern)
            #expect(Grid.quant5(coordinate.lat).bitPattern == item.quant5[1].bitPattern)
        }
    }

    /// The test that justifies ``JSNumber``. A port using `"\(value)"` fails
    /// this on the very first case, where JavaScript writes `139,35` and Swift
    /// would write `139.0,35.0`.
    @Test("coordKey spells a coordinate exactly as JavaScript does")
    func coordinateKeys() throws {
        let fixture = try Self.decode(CoordsFixture.self, "coords.json")
        for item in fixture.cases {
            let coordinate = try #require(Coordinate(pair: item.coord))
            #expect(
                Grid.coordKey(coordinate) == item.coordKey,
                "coordKey(\(item.coord)) — cache identity for this point"
            )
        }
    }

    @Test("segment keys order their two ends the same way")
    func segmentKeys() throws {
        let fixture = try Self.decode(CoordsFixture.self, "coords.json")
        #expect(!fixture.segmentKeys.isEmpty)
        for item in fixture.segmentKeys {
            let a = try #require(Coordinate(pair: item.a))
            let b = try #require(Coordinate(pair: item.b))
            #expect(Grid.routeCoordinateSegmentKey(a, b) == item.key)
            // Direction independence is the property the overlap caches rely
            // on, so it is asserted rather than assumed from the fixture.
            #expect(Grid.routeCoordinateSegmentKey(b, a) == item.key)
        }
    }

    // MARK: - distance

    struct DistanceFixture: Decodable {
        struct Case: Decodable {
            let a: [Double]
            let b: [Double]
            let metres: Double
        }
        let cases: [Case]
    }

    /// A measured ULP budget, not a tolerance picked to make the test pass.
    ///
    /// The first run of this test asserted bit-for-bit equality and found 24
    /// of 803 cases (3.0%) off by 1 or 2 ULP. That was worth chasing, because
    /// the obvious suspect was a transcription slip: the JavaScript writes
    /// `Math.sin(dp / 2) ** 2`, and the first Swift draft wrote
    /// `pow(sin(dp / 2), 2)`. Rewriting it as a plain multiplication changed
    /// nothing — same 24 cases, same 2 ULP — so the residue is not in this
    /// code. It is `sin`/`cos`/`asin` themselves: V8 ships its own
    /// fdlibm-derived implementations and Darwin ships its own, and neither
    /// promises the other's last bit.
    ///
    /// So the budget is 2 ULP, and it is stated in ULP rather than as a
    /// relative epsilon on purpose. At these magnitudes 2 ULP is about
    /// 6 × 10⁻¹⁴ m on a 300 m interval — far below anything the app decides
    /// with, whose tightest threshold is the 2.5 m overlap snap. A relative
    /// epsilon loose enough to absorb a libm difference would also absorb a
    /// wrong Earth radius or a reassociated term; a 2 ULP ceiling cannot.
    ///
    /// If this ever fails, the answer moved for a reason that is not the math
    /// library, and the diff is a real behavioural change.
    @Test("haversine distances match JavaScript within the measured libm budget")
    func distances() throws {
        let fixture = try Self.decode(DistanceFixture.self, "distance.json")
        #expect(fixture.cases.count > 100)

        var worstULP: Int64 = 0
        var worstCase = ""
        var inexact = 0
        for item in fixture.cases {
            let a = try #require(Coordinate(pair: item.a))
            let b = try #require(Coordinate(pair: item.b))
            let got = Geometry.distanceMeters(a, b)
            guard got.bitPattern != item.metres.bitPattern else { continue }
            inexact += 1
            let ulps = abs(
                Int64(bitPattern: got.bitPattern) - Int64(bitPattern: item.metres.bitPattern)
            )
            if ulps > worstULP {
                worstULP = ulps
                worstCase = "distanceMeters(\(item.a), \(item.b)) = \(got) vs \(item.metres)"
            }
        }

        #expect(worstULP <= 2, "worst disagreement \(worstULP) ULP: \(worstCase)")
        // The share that disagrees is itself a signal: it was 3.0% when the
        // budget was set, and a port change that pushes it up is changing the
        // arithmetic even while staying inside the ceiling.
        #expect(
            Double(inexact) / Double(fixture.cases.count) < 0.05,
            "\(inexact)/\(fixture.cases.count) cases inexact — was 24/803 when measured"
        )
    }

    // MARK: - simplification

    struct SimplifyFixture: Decodable {
        struct Case: Decodable {
            let points: [[Double]]
            let epsilonMeters: Double
            let keptIndices: [Int]
        }
        let cases: [Case]
    }

    @Test("Douglas–Peucker keeps the same vertices")
    func simplification() throws {
        let fixture = try Self.decode(SimplifyFixture.self, "simplify.json")
        #expect(fixture.cases.count > 50)
        for item in fixture.cases {
            let points = item.points.compactMap(Coordinate.init(pair:))
            let kept = Geometry.douglasPeuckerIndices(points, epsilonMeters: item.epsilonMeters)
            #expect(
                kept == item.keptIndices,
                "epsilon \(item.epsilonMeters) over \(points.count) points"
            )
        }
    }

    @Test("epsilon 0 retains every index, which lane splitting depends on")
    func zeroEpsilonRetainsEverything() throws {
        let fixture = try Self.decode(SimplifyFixture.self, "simplify.json")
        for item in fixture.cases where item.epsilonMeters == 0 {
            #expect(item.keptIndices == Array(0..<item.points.count))
        }
    }

    // MARK: - compact package intervals

    struct IntervalsFixture: Decodable {
        struct Case: Decodable {
            let country: String
            let lineId: String
            let intervals: [[[Double]]]
        }
        let cases: [Case]
    }

    @Test("decodeIntervals reproduces the drawn geometry vertex for vertex")
    func intervals() throws {
        let fixture = try Self.decode(IntervalsFixture.self, "intervals.json")
        #expect(!fixture.cases.isEmpty)

        for item in fixture.cases {
            let package = try Self.package(country: item.country)
            let line = try #require(
                package.lines.first { $0.id == item.lineId },
                "\(item.country) package has no line \(item.lineId)"
            )
            let decoded = CompactPackage.decodeIntervals(line)

            #expect(
                decoded.count == item.intervals.count,
                "\(item.lineId): interval count"
            )
            for (index, expected) in item.intervals.enumerated() where index < decoded.count {
                let got = decoded[index]
                #expect(
                    got.count == expected.count,
                    "\(item.lineId) interval \(index): vertex count — a missing seam vertex looks like this"
                )
                for (vertex, pair) in expected.enumerated() where vertex < got.count {
                    #expect(got[vertex].lon.bitPattern == pair[0].bitPattern)
                    #expect(got[vertex].lat.bitPattern == pair[1].bitPattern)
                }
            }
        }
    }

    static func package(country: String) throws -> CompactPackage {
        if let cached = packageCache[country] { return cached }
        var directory = URL(filePath: #filePath).deletingLastPathComponent()
        for _ in 0..<8 {
            let candidate = directory.appending(path: "app/public/rail/\(country)-2025.json")
            if FileManager.default.fileExists(atPath: candidate.path) {
                let loaded = try CompactPackage.load(contentsOf: candidate)
                packageCache[country] = loaded
                return loaded
            }
            directory = directory.deletingLastPathComponent()
        }
        throw CocoaError(.fileNoSuchFile)
    }

    nonisolated(unsafe) private static var packageCache: [String: CompactPackage] = [:]
}
