import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const APP_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const ROOT_DIR = path.join(APP_DIR, "..");
const SAMPLE_FILE = path.join(
  ROOT_DIR,
  "samples",
  "jr_limited_shinkansen_itinerary_20260703_20260727_n02_v1_3_expanded_pass_through.json",
);

const TRAIN_KEYS = [
  "id",
  "date",
  "number",
  "train_type",
  "company",
  "origin",
  "destination",
  "direction",
  "visible",
  "style",
  "route_policy",
  "route_sections",
  "stops",
];

const STOP_TYPES = new Set([
  "origin",
  "destination",
  "passenger_stop",
  "operational_stop",
  "pass_through",
]);

async function readJson(filePath) {
  return JSON.parse(await fs.readFile(filePath, "utf8"));
}

test("importable sample is the complete canonical train store", async () => {
  const [store, sample] = await Promise.all([
    readJson(path.join(APP_DIR, "data", "train-store.json")),
    readJson(SAMPLE_FILE),
  ]);

  assert.deepEqual(sample, store);
  assert.equal(sample.schema_version, "1.3");
  assert.ok(sample.trains.length > 0);

  const ids = new Set();
  for (const train of sample.trains) {
    assert.deepEqual(Object.keys(train).sort(), [...TRAIN_KEYS].sort());
    assert.match(train.id, /^[a-zA-Z0-9_-]+$/);
    assert.match(train.date, /^\d{4}-\d{2}-\d{2}$/);
    assert.equal(typeof train.train_type, "string");
    assert.ok(train.train_type.length > 0);
    assert.equal(typeof train.company, "string");
    assert.ok(train.company.length > 0);
    assert.equal(ids.has(train.id), false, `duplicate train id: ${train.id}`);
    ids.add(train.id);

    assert.ok(train.stops.length >= 2);
    assert.equal(train.stops[0].stop_type, "origin");
    assert.equal(train.stops.at(-1).stop_type, "destination");
    assert.equal(train.route_sections.length, train.stops.length - 1);

    train.stops.forEach((stop) => {
      assert.equal(typeof stop.name, "string");
      assert.ok(stop.name.length > 0);
      assert.equal(typeof stop.n02_station_code, "string");
      assert.ok(stop.n02_station_code.length > 0);
      assert.ok(STOP_TYPES.has(stop.stop_type));
      assert.equal(typeof stop.ride_segment, "boolean");
      assert.ok(stop.arrival === null || typeof stop.arrival === "string");
      assert.ok(stop.departure === null || typeof stop.departure === "string");
    });

    train.route_sections.forEach((section, index) => {
      assert.equal(
        section.from_n02_station_code,
        train.stops[index].n02_station_code,
      );
      assert.equal(
        section.to_n02_station_code,
        train.stops[index + 1].n02_station_code,
      );
    });
  }
});

test("Kumamoto weekday tram sample uses the official 2026 timetable minutes", async () => {
  const sample = await readJson(SAMPLE_FILE);
  const byId = new Map(sample.trains.map((train) => [train.id, train]));

  const toKarashimacho = byId.get(
    "20260721_10_kumamoto_tram_a_kumamotoeki_karashimacho",
  );
  assert.ok(toKarashimacho);
  assert.equal(
    toKarashimacho.stops.find((stop) => stop.name === "慶徳校前")?.arrival,
    "17:24",
  );
  assert.equal(
    toKarashimacho.stops.find((stop) => stop.name === "辛島町")?.arrival,
    "17:27",
  );

  const toSuidocho = byId.get(
    "20260721_11_kumamoto_tram_karashimacho_suidocho",
  );
  assert.ok(toSuidocho);
  assert.equal(toSuidocho.stops[0].departure, "17:34");
  assert.equal(
    toSuidocho.stops.find((stop) => stop.name === "熊本城・市役所前")
      ?.arrival,
    "17:37",
  );
  assert.equal(toSuidocho.stops.at(-1).arrival, "17:43");
});

test("precomputed sample parts cover every canonical train with solved geometry", async (t) => {
  let manifest;
  try {
    manifest = await readJson(
      path.join(APP_DIR, "data", "sample-data", "manifest.json"),
    );
  } catch (error) {
    if (error?.code === "ENOENT") {
      t.skip("precomputed sample data is generated by npm run precompute");
      return;
    }
    throw error;
  }

  const store = await readJson(path.join(APP_DIR, "data", "train-store.json"));
  assert.equal(manifest.total, store.trains.length);
  assert.equal(manifest.solved, store.trains.length);
  assert.equal(manifest.unsolvable, 0);
  assert.equal(manifest.no_route, 0);
  assert.equal(manifest.parts.length, store.trains.length);

  const parts = await Promise.all(
    manifest.parts.map((partName) =>
      readJson(
        path.join(APP_DIR, "data", "sample-data", `${partName}.json`),
      ),
    ),
  );
  assert.deepEqual(
    parts.map((part) => part.train.id),
    store.trains.map((train) => train.id),
  );
  parts.forEach((part) => {
    assert.equal(part.format, 1);
    assert.equal(part.route?.unsolvable, undefined);
    assert.equal(typeof part.route?.cache_key, "string");
    assert.ok(part.route.cache_key.length > 0);
    assert.ok(Array.isArray(part.route.features));
    assert.ok(part.route.features.length > 0);
  });

  const indexedParts = Object.values(manifest.dates).flat();
  assert.deepEqual(indexedParts, manifest.parts);
  assert.deepEqual(
    await readJson(
      path.join(APP_DIR, "data", "sample-data", "sample-full.json"),
    ),
    store,
  );
});

test("Hiroden line 1 precomputed route stays on the main-line Hatchobori stop", async (t) => {
  let manifest;
  try {
    manifest = await readJson(
      path.join(APP_DIR, "data", "sample-data", "manifest.json"),
    );
  } catch (error) {
    if (error?.code === "ENOENT") {
      t.skip("precomputed sample data is generated by npm run precompute");
      return;
    }
    throw error;
  }
  const dateParts = await Promise.all(
    (manifest.dates["2026-07-20"] || []).map((partName) =>
      readJson(
        path.join(APP_DIR, "data", "sample-data", `${partName}.json`),
      ),
    ),
  );
  const part = dateParts.find(
    (candidate) =>
      candidate.train.id ===
      "20260720_41_hiroden1_hiroshimaeki_fukuromachi",
  );
  assert.ok(part, "Hiroden line 1 sample part is missing");

  const hatchoboriSegments = part.route.features.filter(
    (feature) =>
      feature.properties.from_n02_station_code === "008058" ||
      feature.properties.to_n02_station_code === "008058",
  );
  assert.equal(hatchoboriSegments.length, 2);
  hatchoboriSegments.forEach((feature) => {
    const gaps = feature.properties.endpoint_display_gap_m;
    assert.ok(
      Math.max(gaps.from, gaps.to) < 60,
      `Hatchobori endpoint jumped off the main line: ${JSON.stringify(gaps)}`,
    );
  });
});
